version: '2'
services:
  data:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    container_name: "mysql"
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_name
      MYSQL_USER: database_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
  redis:
    container_name: "redis"
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
  web:
    container_name: "web"
    build: Dockerfiles/nginx/.
    ports:
      - "80:80"
    expose:
      - "80"
    links:
      - app
  app:
    container_name: "app"
    build: Dockerfiles/php-fpm/.
    volumes:
     - ./application:/var/www/html
    links:
      - mysql
      - redis
    environment:
      APP_DEBUG: 1 #Laravelのエラー制御
      APP_KEY: mwm5RiCU4pnRyPuDzJ7zhisuLq8BJjfV #Laravelのハッシュ、適当に変更して使う
      APP_ENV: develop

      #DB関係
      DB_CONNECTION: "mysql"
      DB_DATABASE: "database_name"
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: "database_user"
      DB_PASSWORD: "password"

      #Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
