version: '2'
services:
  data:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_name
      MYSQL_USER: database_user
      MYSQL_PASSWORD: password
    ports:
      - "3306"
    expose:
      - "3306"
  redis:
    image: redis
  memcached:
    image: memcached
  web:
    container_name: web
    build: Dockerfiles/nginx/.
    ports:
      - "80:80"
    expose:
      - "80"
      - "22"
    links:
      - app
  app:
    container_name: app
    build: Dockerfiles/php-fpm/.
    volumes:
     - ./application:/var/www/html
    links:
      - mysql
      - redis
      - memcached
    environment:
      APP_DEBUG: 1 #Laravelのエラー制御
      APP_KEY: mwm5RiCU4pnRyPuDzJ7zhisuLq8BJjfV #Laravelのハッシュ、適当に変更して使う

      #DB関係
      DB_CONNECTION: "mysql"
      DB_DATABASE: "database_name"
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: "database_user"
      DB_PASSWORD: "password"
